/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package santorini;

import java.awt.Color;
import java.util.Scanner;

/**
 *
 * @author tarri
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    Joueur listeJoueurs[] = new Joueur[2];
    Joueur joueurCourant;
    Grille grilleJeu = new Grille();
    Cellule clic1; // cette variable se verra affecté d'une cellule qui sera la 
    //cellule sur laquelle le joueur cliquera en premier temps pour placer ou deplacer son ouvrier
    Cellule clic2;// cette variable sera la cellule sur laquelle le joueur cliquera en second temps pour construir
    boolean statutDeplacement = false;// le statut deplacement permet de savoir si une première cellule à été selectionnée, false clique 1, true clqiue 2
    boolean statutConstruction = false; // permet de savoir si l'ouvrier doit construire ou se déplacer, false se déplacer, true construire
    Cellule celluleTour = new Cellule();

    public FenetrePrincipale() {
        initComponents();
        PanneauDeJeu.setVisible(false);
        PanneauInfos.setVisible(false);
        PanneauVictoire.setVisible(false);

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {

                CelluleGraphique cellGraph = new CelluleGraphique(grilleJeu.cellule[i][j]);
                cellGraph.addActionListener(new java.awt.event.ActionListener() { // l'écouteur du boutton 

                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Cellule c = cellGraph.celluleAssociee;

                            if (c.constructionMax() == true) {
                                cellGraph.setEnabled(false);
                            }// si la cellule est remplie on ne peut pas cliquer dessus

                            if (statutDeplacement == false && statutConstruction == false) {// si on en est au premier clic
                                statutDeplacement = true;
                                clic1 = c;
                                premierClic(clic1);// place nles ouvriers en début de manche, et vérifie que la case est jouable si les ourviers sont placés
                                victoire();
                            } else if (statutDeplacement == true && statutConstruction == false) {// si on est au second
                                clic2 = c;
                                celluleTour = deplacerOuvrier(clic1, clic2);
                                victoire();
                                //System.out.print("\nJoueur courant : " + joueurCourant.nom + "\nStatut Deplacement : " + statutDeplacement + "\nStatut Construction : " + statutConstruction + "celluleTour : " + celluleTour.ouvrierCourant.joueur + "\n\n");
                            } else if (statutConstruction == true) {
                                construireOuvrier(celluleTour, c);
                                victoire();
                            }
                        }
                    }

                    );
                    PanneauDeJeu.add (cellGraph);
                }
            }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauIntro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanneauVictoire = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomVainqueur = new javax.swing.JLabel();
        finPartie = new javax.swing.JButton();
        Panneau_nom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomJ2 = new javax.swing.JTextField();
        nomJ1 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnValiderNoms = new javax.swing.JButton();
        J1Couleur = new javax.swing.JLabel();
        J2Couleur = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        PanneauDeJeu = new javax.swing.JPanel();
        PanneauInfos = new javax.swing.JPanel();
        txtPI = new javax.swing.JLabel();
        nomJoueurCourant = new javax.swing.JLabel();
        txtInfos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauIntro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SANTOPYRAMID");

        javax.swing.GroupLayout PanneauIntroLayout = new javax.swing.GroupLayout(PanneauIntro);
        PanneauIntro.setLayout(PanneauIntroLayout);
        PanneauIntroLayout.setHorizontalGroup(
            PanneauIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanneauIntroLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        PanneauIntroLayout.setVerticalGroup(
            PanneauIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauIntroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(PanneauIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        PanneauVictoire.setBackground(new java.awt.Color(255, 255, 255));
        PanneauVictoire.setVerifyInputWhenFocusTarget(false);

        jLabel6.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("VICTOIRE ");

        jLabel7.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("DE");

        nomVainqueur.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        nomVainqueur.setForeground(new java.awt.Color(0, 0, 0));
        nomVainqueur.setText("Nom Vainqueur");

        finPartie.setBackground(new java.awt.Color(255, 255, 255));
        finPartie.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        finPartie.setForeground(new java.awt.Color(0, 0, 0));
        finPartie.setText("CONTINUER");
        finPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finPartieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanneauVictoireLayout = new javax.swing.GroupLayout(PanneauVictoire);
        PanneauVictoire.setLayout(PanneauVictoireLayout);
        PanneauVictoireLayout.setHorizontalGroup(
            PanneauVictoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauVictoireLayout.createSequentialGroup()
                .addGroup(PanneauVictoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanneauVictoireLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel6))
                    .addGroup(PanneauVictoireLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(nomVainqueur))
                    .addGroup(PanneauVictoireLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel7))
                    .addGroup(PanneauVictoireLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(finPartie)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PanneauVictoireLayout.setVerticalGroup(
            PanneauVictoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauVictoireLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(nomVainqueur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(finPartie)
                .addGap(102, 102, 102))
        );

        getContentPane().add(PanneauVictoire, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 600));

        Panneau_nom.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Jouieur 1 : ");

        jLabel2.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Jouieur 2 : ");

        nomJ2.setBackground(new java.awt.Color(255, 255, 255));
        nomJ2.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        nomJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJ2ActionPerformed(evt);
            }
        });

        nomJ1.setBackground(new java.awt.Color(255, 255, 255));
        nomJ1.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        nomJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJ1ActionPerformed(evt);
            }
        });

        btn_start.setBackground(new java.awt.Color(255, 255, 255));
        btn_start.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        btn_start.setForeground(new java.awt.Color(0, 0, 0));
        btn_start.setText("Lancer Partie ");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Couleur  Joueur 1 :");

        jLabel5.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Couleur Joueur 2 : ");

        btnValiderNoms.setBackground(new java.awt.Color(255, 255, 255));
        btnValiderNoms.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N
        btnValiderNoms.setForeground(new java.awt.Color(0, 0, 0));
        btnValiderNoms.setText("Valider");
        btnValiderNoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderNomsActionPerformed(evt);
            }
        });

        J1Couleur.setBackground(new java.awt.Color(255, 255, 255));
        J1Couleur.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        J1Couleur.setForeground(new java.awt.Color(0, 0, 0));

        J2Couleur.setBackground(new java.awt.Color(255, 255, 255));
        J2Couleur.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        J2Couleur.setForeground(new java.awt.Color(0, 0, 0));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox11.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox12.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox12.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox13.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox13.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });

        jCheckBox14.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox14.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox15.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panneau_nomLayout = new javax.swing.GroupLayout(Panneau_nom);
        Panneau_nom.setLayout(Panneau_nomLayout);
        Panneau_nomLayout.setHorizontalGroup(
            Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panneau_nomLayout.createSequentialGroup()
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(J2Couleur, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panneau_nomLayout.createSequentialGroup()
                                .addComponent(jCheckBox15)
                                .addGap(70, 70, 70)
                                .addComponent(jCheckBox14)
                                .addGap(70, 70, 70)
                                .addComponent(jCheckBox11)
                                .addGap(70, 70, 70)
                                .addComponent(jCheckBox13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(jCheckBox12))
                            .addGroup(Panneau_nomLayout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(70, 70, 70)
                                .addComponent(jCheckBox7)
                                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(J1Couleur, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jCheckBox3)
                                        .addGap(70, 70, 70)
                                        .addComponent(jCheckBox6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                        .addComponent(jCheckBox5)
                                        .addGap(18, 18, 18)))))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(Panneau_nomLayout.createSequentialGroup()
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(btnValiderNoms, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panneau_nomLayout.createSequentialGroup()
                                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomJ2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(nomJ1)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panneau_nomLayout.setVerticalGroup(
            Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panneau_nomLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnValiderNoms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox7))
                .addGap(12, 12, 12)
                .addComponent(J1Couleur, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox14))
                .addGap(21, 21, 21)
                .addComponent(J2Couleur, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(Panneau_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 600));

        PanneauDeJeu.setBackground(new java.awt.Color(204, 255, 255));
        PanneauDeJeu.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(PanneauDeJeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 500));

        PanneauInfos.setBackground(new java.awt.Color(255, 255, 255));

        txtPI.setBackground(new java.awt.Color(255, 255, 255));
        txtPI.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        txtPI.setText("C'est à :");

        nomJoueurCourant.setBackground(new java.awt.Color(255, 255, 255));
        nomJoueurCourant.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N

        txtInfos.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N

        javax.swing.GroupLayout PanneauInfosLayout = new javax.swing.GroupLayout(PanneauInfos);
        PanneauInfos.setLayout(PanneauInfosLayout);
        PanneauInfosLayout.setHorizontalGroup(
            PanneauInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanneauInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanneauInfosLayout.createSequentialGroup()
                        .addComponent(txtPI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomJoueurCourant, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanneauInfosLayout.setVerticalGroup(
            PanneauInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanneauInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomJoueurCourant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanneauInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 500, 100));

        setBounds(0, 0, 518, 746);
    }// </editor-fold>//GEN-END:initComponents

    private void nomJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomJ1ActionPerformed

    private void nomJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomJ2ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        Panneau_nom.setVisible(false);
        PanneauDeJeu.setVisible(true);
        PanneauInfos.setVisible(true);
        
    }//GEN-LAST:event_btn_startActionPerformed

    private void btnValiderNomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderNomsActionPerformed

        nomJ1.setEnabled(false);// on bloque la saisie des noms
        nomJ2.setEnabled(false);
        btnValiderNoms.setEnabled(false);
        initialiserPartie();
        J1Couleur.setText(listeJoueurs[0].couleur + "");
        J2Couleur.setText(listeJoueurs[1].couleur + "");
        

    }//GEN-LAST:event_btnValiderNomsActionPerformed

    private void finPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finPartieActionPerformed
        PanneauVictoire.setVisible(false);
        Panneau_nom.setVisible(true);
        nomJ1.setEnabled(true);// on active la saisie des noms
        nomJ2.setEnabled(true);
        nomJ1.setText("");
        nomJ2.setText("");
        listeJoueurs[0] = null;
        listeJoueurs[1] = null;
        btnValiderNoms.setEnabled(true);
    }//GEN-LAST:event_finPartieActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    void attribuerCouleur() {
        listeJoueurs[0].affecterCouleur("rouge");
        listeJoueurs[1].affecterCouleur("bleu");
    }

    void initialiserPartie() {
        // on vide la grille
        grilleJeu.viderGrille();

        statutDeplacement = false;

        //on demande les noms des joueurs
        String nomJoueur1 = nomJ1.getText();
        String nomJoueur2 = nomJ2.getText();
        listeJoueurs[0] = new Joueur(nomJoueur1);
        listeJoueurs[1] = new Joueur(nomJoueur2);
        joueurCourant = listeJoueurs[0];
        attribuerCouleur();

    }

    public void victoire(){
        if(grilleJeu.etreGagnant(joueurCourant) == true){
            nomVainqueur.setText(joueurCourant.nom);
            PanneauDeJeu.setVisible(false);
            PanneauInfos.setVisible(false);
            PanneauVictoire.setVisible(true);
        }else if(grilleJeu.etrePerdant(joueurCourant) == true){
            prochainJoueur();
            nomVainqueur.setText(joueurCourant.nom);
            PanneauDeJeu.setVisible(false);
            PanneauInfos.setVisible(false);
            PanneauVictoire.setVisible(true);
        }
    }

    public void premierClic(Cellule uneCellule) {
        // Les ouvriers se créent lorsque le joueur les place,
        //la foncion prends en entrée une cellule place un ouvrier dessus si le joueur peut 
        if (uneCellule.celluleLibre() == true) {
            if (joueurCourant.ouvriers[0] == null) {
                joueurCourant.ouvriers[0] = new Ouvrier(joueurCourant);
                uneCellule.ouvrierCourant = joueurCourant.ouvriers[0];
                prochainJoueur();
                statutDeplacement = false;
                return;
            } else if (joueurCourant.ouvriers[0] != null && joueurCourant.ouvriers[1] == null) {
                joueurCourant.ouvriers[1] = new Ouvrier(joueurCourant);
                uneCellule.ouvrierCourant = joueurCourant.ouvriers[1];
                prochainJoueur();
                statutDeplacement = false;
                return;
            }
        }
        if (listeJoueurs[0].avoirSesOuvriers() == true && listeJoueurs[1].avoirSesOuvriers() == true) {
            if (uneCellule.presenceJoueur(joueurCourant) != true) { // si la case n'appartient pas au joueur courant on refait le premier clic
                statutDeplacement = false;
                txtInfos.setText("Selectionnez un ouvrier ("+joueurCourant.couleur+")\nEssayez encore !");
            }else{
                txtInfos.setText("Choisissez la case où déplacer votre ouvrier.");
            }
        }
    }

    public Cellule deplacerOuvrier(Cellule celluleDepart, Cellule celluleArrivee) {
        /*  on vérifie si le déplacement est possible
        on renvoie l'ouvrier courant si le déplacement s'est fait et null sinon*/
        if (celluleDepart.presenceJoueur(joueurCourant) == true && grilleJeu.deplacementPossible(celluleDepart, celluleArrivee) == true) {
            celluleArrivee.affecterOuvrier(celluleDepart.recupererOuvrier());
            PanneauDeJeu.repaint();
            statutDeplacement = false;
            statutConstruction = true;
            txtInfos.setText("Construisez sur une case en cliquant dessus");
            return celluleArrivee;
        }
        statutDeplacement = false;

        return null;
    }

    public void construireOuvrier(Cellule celluleOuvrier, Cellule celluleConst) {
        /*prends en entrée un ouvrier (celui qui vient de se déplacer) courant et la cellule qui doit etre Construite
        renvoie true si la construciton s'est faite et false sinon*/
        if (celluleOuvrier == null) {
            return;
        }

        if (grilleJeu.constructionPossible(celluleOuvrier, celluleConst) == true) {
            celluleConst.construire();
            prochainJoueur();
            clic1 = null;
            clic2 = null;
            PanneauDeJeu.repaint();
            statutConstruction = false;
            statutDeplacement = false;
        }
    }


    public void prochainJoueur() {// permet de passer au joueur 
        if (joueurCourant == listeJoueurs[0]) {
            joueurCourant = listeJoueurs[1];
        } else {
            joueurCourant = listeJoueurs[0];
        }
        nomJoueurCourant.setText(joueurCourant.nom + "");
        txtInfos.setText("Cliquez sur un ouvrier ("+joueurCourant.couleur+")");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J1Couleur;
    private javax.swing.JLabel J2Couleur;
    private javax.swing.JPanel PanneauDeJeu;
    private javax.swing.JPanel PanneauInfos;
    private javax.swing.JPanel PanneauIntro;
    private javax.swing.JPanel PanneauVictoire;
    private javax.swing.JPanel Panneau_nom;
    private javax.swing.JButton btnValiderNoms;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton finPartie;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nomJ1;
    private javax.swing.JTextField nomJ2;
    private javax.swing.JLabel nomJoueurCourant;
    private javax.swing.JLabel nomVainqueur;
    private javax.swing.JLabel txtInfos;
    private javax.swing.JLabel txtPI;
    // End of variables declaration//GEN-END:variables
}
