/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package santorini;

import java.awt.Color;
import java.util.Scanner;

/**
 *
 * @author tarri
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    Joueur listeJoueurs[] = new Joueur[2];
    Joueur joueurCourant;
    Grille grilleJeu = new Grille();
    Cellule clic1; // cette variable se verra affecté d'une cellule qui sera la 
    //cellule sur laquelle le joueur cliquera en premier temps pour placer ou deplacer son ouvrier
    Cellule clic2;// cette variable sera la cellule sur laquelle le joueur cliquera en second temps pour construir
    boolean statutDeplacement = false;// le statut deplacement permet de savoir si une première cellule à été selectionnée, false clique 1, true clqiue 2
    boolean statutConstruction = false; // permet de savoir si l'ouvrier doit construire ou se déplacer, false se déplacer, true construire
    Cellule celluleTour = new Cellule();

    public FenetrePrincipale() {
        initComponents();
        PanneauDeJeu.setVisible(false);
        PanneauInfos.setVisible(false);
        PanneauVictoire.setVisible(false);

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {

                CelluleGraphique cellGraph = new CelluleGraphique(grilleJeu.cellule[i][j]);
                cellGraph.addActionListener(new java.awt.event.ActionListener() { // l'écouteur du boutton 

                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Cellule c = cellGraph.celluleAssociee;

                            if (c.constructionMax() == true) {
                                cellGraph.setEnabled(false);
                            }// si la cellule est remplie on ne peut pas cliquer dessus

                            if (statutDeplacement == false && statutConstruction == false) {// si on en est au premier clic
                                statutDeplacement = true;
                                clic1 = c;
                                premierClic(clic1);// place nles ouvriers en début de manche, et vérifie que la case est jouable si les ourviers sont placés
                                victoire();
                            } else if (statutDeplacement == true && statutConstruction == false) {// si on est au second
                                clic2 = c;
                                celluleTour = deplacerOuvrier(clic1, clic2);
                                victoire();
                                //System.out.print("\nJoueur courant : " + joueurCourant.nom + "\nStatut Deplacement : " + statutDeplacement + "\nStatut Construction : " + statutConstruction + "celluleTour : " + celluleTour.ouvrierCourant.joueur + "\n\n");
                            } else if (statutConstruction == true) {
                                construireOuvrier(celluleTour, c);
                                victoire();
                            }
                        }
                    }

                    );
                    PanneauDeJeu.add (cellGraph);
                }
            }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauIntro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanneauVictoire = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomVainqueur = new javax.swing.JLabel();
        finPartie = new javax.swing.JButton();
        Panneau_nom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomJ2 = new javax.swing.JTextField();
        nomJ1 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        btnValiderNoms = new javax.swing.JButton();
        rougeJ2 = new javax.swing.JButton();
        bleuJ2 = new javax.swing.JButton();
        jauneJ2 = new javax.swing.JButton();
        roseJ2 = new javax.swing.JButton();
        turquoiseJ2 = new javax.swing.JButton();
        rougeJ1 = new javax.swing.JButton();
        bleuJ1 = new javax.swing.JButton();
        jauneJ1 = new javax.swing.JButton();
        roseJ1 = new javax.swing.JButton();
        turquoiseJ1 = new javax.swing.JButton();
        couleurJ1 = new javax.swing.JLabel();
        couleurJ2 = new javax.swing.JLabel();
        txtCouleurJ2 = new javax.swing.JLabel();
        txtCouleurJ1 = new javax.swing.JLabel();
        PanneauDeJeu = new javax.swing.JPanel();
        PanneauInfos = new javax.swing.JPanel();
        txtPI = new javax.swing.JLabel();
        nomJoueurCourant = new javax.swing.JLabel();
        txtInfos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauIntro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SANTOPYRAMID");

        javax.swing.GroupLayout PanneauIntroLayout = new javax.swing.GroupLayout(PanneauIntro);
        PanneauIntro.setLayout(PanneauIntroLayout);
        PanneauIntroLayout.setHorizontalGroup(
            PanneauIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanneauIntroLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        PanneauIntroLayout.setVerticalGroup(
            PanneauIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauIntroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(PanneauIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        PanneauVictoire.setBackground(new java.awt.Color(255, 255, 255));
        PanneauVictoire.setVerifyInputWhenFocusTarget(false);

        jLabel6.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("VICTOIRE ");

        jLabel7.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("DE");

        nomVainqueur.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        nomVainqueur.setForeground(new java.awt.Color(0, 0, 0));
        nomVainqueur.setText("Nom Vainqueur");

        finPartie.setBackground(new java.awt.Color(255, 255, 255));
        finPartie.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        finPartie.setForeground(new java.awt.Color(0, 0, 0));
        finPartie.setText("CONTINUER");
        finPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finPartieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanneauVictoireLayout = new javax.swing.GroupLayout(PanneauVictoire);
        PanneauVictoire.setLayout(PanneauVictoireLayout);
        PanneauVictoireLayout.setHorizontalGroup(
            PanneauVictoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauVictoireLayout.createSequentialGroup()
                .addGroup(PanneauVictoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanneauVictoireLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel6))
                    .addGroup(PanneauVictoireLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(nomVainqueur))
                    .addGroup(PanneauVictoireLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel7))
                    .addGroup(PanneauVictoireLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(finPartie)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PanneauVictoireLayout.setVerticalGroup(
            PanneauVictoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauVictoireLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(nomVainqueur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(finPartie)
                .addGap(102, 102, 102))
        );

        getContentPane().add(PanneauVictoire, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 600));

        Panneau_nom.setBackground(new java.awt.Color(255, 255, 255));
        Panneau_nom.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Joueur 1 : ");

        jLabel2.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Joueur 2 : ");

        nomJ2.setBackground(new java.awt.Color(255, 255, 255));
        nomJ2.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        nomJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJ2ActionPerformed(evt);
            }
        });

        nomJ1.setBackground(new java.awt.Color(255, 255, 255));
        nomJ1.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        nomJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJ1ActionPerformed(evt);
            }
        });

        btn_start.setBackground(new java.awt.Color(255, 255, 255));
        btn_start.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        btn_start.setForeground(new java.awt.Color(0, 0, 0));
        btn_start.setText("Lancer Partie ");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        btnValiderNoms.setBackground(new java.awt.Color(255, 255, 255));
        btnValiderNoms.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N
        btnValiderNoms.setForeground(new java.awt.Color(0, 0, 0));
        btnValiderNoms.setText("Valider");
        btnValiderNoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderNomsActionPerformed(evt);
            }
        });

        rougeJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurRouge.jpg"))); // NOI18N
        rougeJ2.setToolTipText("");
        rougeJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rougeJ2ActionPerformed(evt);
            }
        });

        bleuJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurBleu.jpg"))); // NOI18N
        bleuJ2.setToolTipText("");
        bleuJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bleuJ2ActionPerformed(evt);
            }
        });

        jauneJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurJaune.jpg"))); // NOI18N
        jauneJ2.setToolTipText("");
        jauneJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jauneJ2ActionPerformed(evt);
            }
        });

        roseJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurRose.jpg"))); // NOI18N
        roseJ2.setToolTipText("");
        roseJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roseJ2ActionPerformed(evt);
            }
        });

        turquoiseJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurTurquoise.jpg"))); // NOI18N
        turquoiseJ2.setToolTipText("");
        turquoiseJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turquoiseJ2ActionPerformed(evt);
            }
        });

        rougeJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurRouge.jpg"))); // NOI18N
        rougeJ1.setToolTipText("");
        rougeJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rougeJ1ActionPerformed(evt);
            }
        });

        bleuJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurBleu.jpg"))); // NOI18N
        bleuJ1.setToolTipText("");
        bleuJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bleuJ1ActionPerformed(evt);
            }
        });

        jauneJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurJaune.jpg"))); // NOI18N
        jauneJ1.setToolTipText("");
        jauneJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jauneJ1ActionPerformed(evt);
            }
        });

        roseJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurRose.jpg"))); // NOI18N
        roseJ1.setToolTipText("");
        roseJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roseJ1ActionPerformed(evt);
            }
        });

        turquoiseJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couleurTurquoise.jpg"))); // NOI18N
        turquoiseJ1.setToolTipText("");
        turquoiseJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turquoiseJ1ActionPerformed(evt);
            }
        });

        couleurJ1.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        couleurJ1.setForeground(new java.awt.Color(0, 0, 0));

        couleurJ2.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        couleurJ2.setForeground(new java.awt.Color(0, 0, 0));

        txtCouleurJ2.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        txtCouleurJ2.setForeground(new java.awt.Color(0, 0, 0));
        txtCouleurJ2.setText("Couleur Joueur 2 : ");

        txtCouleurJ1.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        txtCouleurJ1.setForeground(new java.awt.Color(0, 0, 0));
        txtCouleurJ1.setText("Couleur  Joueur 1 :");

        javax.swing.GroupLayout Panneau_nomLayout = new javax.swing.GroupLayout(Panneau_nom);
        Panneau_nom.setLayout(Panneau_nomLayout);
        Panneau_nomLayout.setHorizontalGroup(
            Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panneau_nomLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addComponent(txtCouleurJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panneau_nomLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(btnValiderNoms, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panneau_nomLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(couleurJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomJ2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(nomJ1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panneau_nomLayout.createSequentialGroup()
                        .addComponent(txtCouleurJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(couleurJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(Panneau_nomLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addComponent(rougeJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(bleuJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jauneJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(roseJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(turquoiseJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panneau_nomLayout.createSequentialGroup()
                        .addComponent(rougeJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(bleuJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jauneJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(roseJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(turquoiseJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panneau_nomLayout.setVerticalGroup(
            Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panneau_nomLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnValiderNoms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCouleurJ1)
                    .addComponent(couleurJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rougeJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bleuJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jauneJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roseJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turquoiseJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(couleurJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCouleurJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panneau_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rougeJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bleuJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jauneJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roseJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turquoiseJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(Panneau_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 600));

        PanneauDeJeu.setBackground(new java.awt.Color(204, 255, 255));
        PanneauDeJeu.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(PanneauDeJeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 500));

        PanneauInfos.setBackground(new java.awt.Color(255, 255, 255));

        txtPI.setBackground(new java.awt.Color(255, 255, 255));
        txtPI.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        txtPI.setText("C'est à :");

        nomJoueurCourant.setBackground(new java.awt.Color(255, 255, 255));
        nomJoueurCourant.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N

        txtInfos.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N

        javax.swing.GroupLayout PanneauInfosLayout = new javax.swing.GroupLayout(PanneauInfos);
        PanneauInfos.setLayout(PanneauInfosLayout);
        PanneauInfosLayout.setHorizontalGroup(
            PanneauInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanneauInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanneauInfosLayout.createSequentialGroup()
                        .addComponent(txtPI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomJoueurCourant, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanneauInfosLayout.setVerticalGroup(
            PanneauInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanneauInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanneauInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomJoueurCourant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanneauInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 500, 100));

        setBounds(0, 0, 518, 746);
    }// </editor-fold>//GEN-END:initComponents

    private void finPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finPartieActionPerformed
        PanneauVictoire.setVisible(false);
        Panneau_nom.setVisible(true);
        nomJ1.setEnabled(true);// on active la saisie des noms
        nomJ2.setEnabled(true);
        nomJ1.setText("");
        nomJ2.setText("");
        listeJoueurs[0] = null;
        listeJoueurs[1] = null;
        btnValiderNoms.setEnabled(true);
    }//GEN-LAST:event_finPartieActionPerformed

    private void btnValiderNomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderNomsActionPerformed

        nomJ1.setEnabled(false);// on bloque la saisie des noms
        nomJ2.setEnabled(false);
        btnValiderNoms.setEnabled(false);
        initialiserPartie();
        

    }//GEN-LAST:event_btnValiderNomsActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        if(listeJoueurs[0].couleur != listeJoueurs[1].couleur && listeJoueurs[0].couleur != null && listeJoueurs[1].couleur != null){ // on vérifie que les deux couleurs ne sont pas les mêmes
            Panneau_nom.setVisible(false);
            PanneauDeJeu.setVisible(true);
            PanneauInfos.setVisible(true);
        }   

    }//GEN-LAST:event_btn_startActionPerformed

    private void nomJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJ1ActionPerformed
    }//GEN-LAST:event_nomJ1ActionPerformed

    private void nomJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJ2ActionPerformed
    }//GEN-LAST:event_nomJ2ActionPerformed

    private void rougeJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rougeJ1ActionPerformed
    listeJoueurs[0].affecterCouleur("rouge");
    couleurJ1.setText("ROUGE");
    }//GEN-LAST:event_rougeJ1ActionPerformed

    private void bleuJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bleuJ1ActionPerformed
    listeJoueurs[0].affecterCouleur("bleu");
    couleurJ1.setText("BLEU");
    }//GEN-LAST:event_bleuJ1ActionPerformed

    private void jauneJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jauneJ1ActionPerformed
    listeJoueurs[0].affecterCouleur("jaune");
    couleurJ1.setText("JAUNE");
    }//GEN-LAST:event_jauneJ1ActionPerformed

    private void roseJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roseJ1ActionPerformed
    listeJoueurs[0].affecterCouleur("rose");
    couleurJ1.setText("ROSE");
    }//GEN-LAST:event_roseJ1ActionPerformed

    private void turquoiseJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turquoiseJ1ActionPerformed
    listeJoueurs[0].affecterCouleur("turquoise");
    couleurJ1.setText("TURQUOISE");    }//GEN-LAST:event_turquoiseJ1ActionPerformed

    private void rougeJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rougeJ2ActionPerformed
    listeJoueurs[1].affecterCouleur("rouge");
    couleurJ2.setText("ROUGE");    }//GEN-LAST:event_rougeJ2ActionPerformed

    private void bleuJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bleuJ2ActionPerformed
    listeJoueurs[1].affecterCouleur("bleu");
    couleurJ2.setText("BLEU");    }//GEN-LAST:event_bleuJ2ActionPerformed

    private void jauneJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jauneJ2ActionPerformed
    listeJoueurs[1].affecterCouleur("jaune");
    couleurJ2.setText("JAUNE");    }//GEN-LAST:event_jauneJ2ActionPerformed

    private void roseJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roseJ2ActionPerformed
    listeJoueurs[1].affecterCouleur("rose");
    couleurJ2.setText("ROSE");    }//GEN-LAST:event_roseJ2ActionPerformed

    private void turquoiseJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turquoiseJ2ActionPerformed
    listeJoueurs[1].affecterCouleur("turquoise");
    couleurJ2.setText("TURQUOISE");    }//GEN-LAST:event_turquoiseJ2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    void attribuerCouleur() {
        listeJoueurs[0].affecterCouleur("rouge");
        listeJoueurs[1].affecterCouleur("bleu");
    }

    void initialiserPartie() {
        // on vide la grille
        grilleJeu.viderGrille();

        statutDeplacement = false;

        //on demande les noms des joueurs
        String nomJoueur1 = nomJ1.getText();
        String nomJoueur2 = nomJ2.getText();
        listeJoueurs[0] = new Joueur(nomJoueur1);
        listeJoueurs[1] = new Joueur(nomJoueur2);
        joueurCourant = listeJoueurs[0];
        attribuerCouleur();

    }

    public void victoire(){
        if(grilleJeu.etreGagnant(joueurCourant) == true){
            nomVainqueur.setText(joueurCourant.nom);
            PanneauDeJeu.setVisible(false);
            PanneauInfos.setVisible(false);
            PanneauVictoire.setVisible(true);
        }else if(grilleJeu.etrePerdant(joueurCourant) == true){
            prochainJoueur();
            nomVainqueur.setText(joueurCourant.nom);
            PanneauDeJeu.setVisible(false);
            PanneauInfos.setVisible(false);
            PanneauVictoire.setVisible(true);
        }
    }

    public void premierClic(Cellule uneCellule) {
        // Les ouvriers se créent lorsque le joueur les place,
        //la foncion prends en entrée une cellule place un ouvrier dessus si le joueur peut 
        if (uneCellule.celluleLibre() == true) {
            if (joueurCourant.ouvriers[0] == null) {
                joueurCourant.ouvriers[0] = new Ouvrier(joueurCourant);
                uneCellule.ouvrierCourant = joueurCourant.ouvriers[0];
                prochainJoueur();
                statutDeplacement = false;
                return;
            } else if (joueurCourant.ouvriers[0] != null && joueurCourant.ouvriers[1] == null) {
                joueurCourant.ouvriers[1] = new Ouvrier(joueurCourant);
                uneCellule.ouvrierCourant = joueurCourant.ouvriers[1];
                prochainJoueur();
                statutDeplacement = false;
                return;
            }
        }
        if (listeJoueurs[0].avoirSesOuvriers() == true && listeJoueurs[1].avoirSesOuvriers() == true) {
            if (uneCellule.presenceJoueur(joueurCourant) != true) { // si la case n'appartient pas au joueur courant on refait le premier clic
                statutDeplacement = false;
                txtInfos.setText("Selectionnez un ouvrier ("+joueurCourant.couleur+")\nEssayez encore !");
            }else{
                txtInfos.setText("Choisissez la case où déplacer votre ouvrier.");
            }
        }
    }

    public Cellule deplacerOuvrier(Cellule celluleDepart, Cellule celluleArrivee) {
        /*  on vérifie si le déplacement est possible
        on renvoie l'ouvrier courant si le déplacement s'est fait et null sinon*/
        if (celluleDepart.presenceJoueur(joueurCourant) == true && grilleJeu.deplacementPossible(celluleDepart, celluleArrivee) == true) {
            celluleArrivee.affecterOuvrier(celluleDepart.recupererOuvrier());
            PanneauDeJeu.repaint();
            statutDeplacement = false;
            statutConstruction = true;
            txtInfos.setText("Construisez sur une case en cliquant dessus");
            return celluleArrivee;
        }
        statutDeplacement = false;

        return null;
    }

    public void construireOuvrier(Cellule celluleOuvrier, Cellule celluleConst) {
        /*prends en entrée un ouvrier (celui qui vient de se déplacer) courant et la cellule qui doit etre Construite
        renvoie true si la construciton s'est faite et false sinon*/
        if (celluleOuvrier == null) {
            return;
        }

        if (grilleJeu.constructionPossible(celluleOuvrier, celluleConst) == true) {
            celluleConst.construire();
            prochainJoueur();
            clic1 = null;
            clic2 = null;
            PanneauDeJeu.repaint();
            statutConstruction = false;
            statutDeplacement = false;
        }
    }


    public void prochainJoueur() {// permet de passer au joueur 
        if (joueurCourant == listeJoueurs[0]) {
            joueurCourant = listeJoueurs[1];
        } else {
            joueurCourant = listeJoueurs[0];
        }
        nomJoueurCourant.setText(joueurCourant.nom + "");
        txtInfos.setText("Cliquez sur un ouvrier ("+joueurCourant.couleur+")");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauDeJeu;
    private javax.swing.JPanel PanneauInfos;
    private javax.swing.JPanel PanneauIntro;
    private javax.swing.JPanel PanneauVictoire;
    private javax.swing.JPanel Panneau_nom;
    private javax.swing.JButton bleuJ1;
    private javax.swing.JButton bleuJ2;
    private javax.swing.JButton btnValiderNoms;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel couleurJ1;
    private javax.swing.JLabel couleurJ2;
    private javax.swing.JButton finPartie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jauneJ1;
    private javax.swing.JButton jauneJ2;
    private javax.swing.JTextField nomJ1;
    private javax.swing.JTextField nomJ2;
    private javax.swing.JLabel nomJoueurCourant;
    private javax.swing.JLabel nomVainqueur;
    private javax.swing.JButton roseJ1;
    private javax.swing.JButton roseJ2;
    private javax.swing.JButton rougeJ1;
    private javax.swing.JButton rougeJ2;
    private javax.swing.JButton turquoiseJ1;
    private javax.swing.JButton turquoiseJ2;
    private javax.swing.JLabel txtCouleurJ1;
    private javax.swing.JLabel txtCouleurJ2;
    private javax.swing.JLabel txtInfos;
    private javax.swing.JLabel txtPI;
    // End of variables declaration//GEN-END:variables
}
